name: Limit Open PRs

on:
    pull_request:
        types: [opened, reopened, synchronize]

jobs:
    limit-prs:
        runs-on: ubuntu-latest
        steps:
            - name: Check number of non-draft open PRs and manage
              run: |
                  # Get the number of open non-draft PRs
                  PR_COUNT=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    "https://api.github.com/repos/${{ github.repository }}/pulls?state=open" | jq '[.[] | select(.draft == false)] | length')
                  echo "Open non-draft PRs: $PR_COUNT"

                  # If limit is exceeded, comment and close the PR
                  if [[ "$PR_COUNT" -gt 5 ]]; then
                    PR_NUMBER=${{ github.event.pull_request.number }}

                    # Check if the current PR is a draft
                    if [ "${{ github.event.pull_request.draft }}" == "false" ]; then
                      # Add a comment to the PR
                      curl -X POST -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments" \
                        -d '{"body": "This pull request is being closed because there are already 5 open non-draft pull requests. Please reopen or create a new pull request once there is an available spot."}'

                      # Close the PR
                      curl -X PATCH -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                        -H "Accept: application/vnd.github.v3+json" \
                        "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER" \
                        -d '{"state": "closed"}'
                    fi
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
